language: java 
script: mvn package

after_script:
  - cd ./target
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add demo-0.0.1-SNAPSHOT.jar
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}